version: "3.7"
services:
  apim:
    image: wso2/wso2am:4.1.0-alpine
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9444"]
      interval: 10s
      retries: 50
    ports:
      - "9444:9444"
    environment:
      - PROFILE_NAME=control-plane
    volumes:
      - ./conf/deployment.toml:/home/wso2carbon/wso2-config-volume/repository/conf/deployment.toml
      - ./resources/controlplane/lib/postgresql-42.3.6.jar:/home/wso2carbon/wso2-config-volume/repository/components/lib/postgresql-42.3.6.jar
      - ./resources/controlplane/security/keystore/wso2carbon_tls.jks:/home/wso2carbon/wso2-config-volume/repository/resources/security/wso2carbon_tls.jks
      - ./resources/controlplane/security/keystore/wso2carbon_internal.jks:/home/wso2carbon/wso2-config-volume/repository/resources/security/wso2carbon_internal.jks
      - ./resources/controlplane/bin/api-manager.sh:/home/wso2carbon/wso2-config-volume/bin/api-manager.sh
    hostname: hostname.docker.otw.net.au
  api-controller:
    build: ./docker/api-controller
    image: wso2/api-controller
    hostname: api-controller
    depends_on:
      - apim
    volumes:
      - ./docker/openapi-specs/:/tmp/openapi-specs/
    command: ["/usr/local/bin/init.sh"]
  router:
    image: wso2/choreo-connect-router:1.1.0
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    environment:
      - ROUTER_ADMIN_HOST=0.0.0.0
      - ROUTER_ADMIN_PORT=9000
      - ROUTER_CLUSTER=default_cluster
      - ROUTER_LABEL=Default
      - ROUTER_PRIVATE_KEY_PATH=/home/wso2/security/keystore/mg.key
      - ROUTER_PUBLIC_CERT_PATH=/home/wso2/security/keystore/mg.pem
      - ADAPTER_HOST=adapter
      - ADAPTER_PORT=18000
      - ADAPTER_CA_CERT_PATH=/home/wso2/security/truststore/mg.pem
      - ENFORCER_HOST=enforcer
      - ENFORCER_PORT=8081
      - ENFORCER_CA_CERT_PATH=/home/wso2/security/truststore/mg.pem
      - CONCURRENCY=2
    volumes:
      - ./resources/router/security:/home/wso2/security
    ports:
      - "19095:9095"
      - "19000:9000"
      - "19090:9090"
    links:
      - adapter
      - enforcer
  adapter:
    image: wso2/choreo-connect-adapter:1.1.0
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./resources/adapter/security:/home/wso2/security
      - ./conf/log_config.toml:/home/wso2/conf/log_config.toml
      - ./conf/config.toml:/home/wso2/conf/config.toml
    environment:
      - ADAPTER_PRIVATE_KEY_PATH=/home/wso2/security/keystore/mg.key
      - ADAPTER_PUBLIC_CERT_PATH=/home/wso2/security/keystore/mg.pem
      - cp_admin_pwd=admin
      - adapter_admin_pwd=admin
#    ports:
#      - "18000:18000"
#      - "19843:9843"
    links:
      - apim
  enforcer:
    image: wso2/choreo-connect-enforcer:1.1.0
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./resources/enforcer/security:/home/wso2/security
      - ./conf/log4j2.properties:/home/wso2/conf/log4j2.properties
      #- ./resources/enforcer/dropins:/home/wso2/lib/dropins
    links:
      - adapter
      - apim
    environment:
      - ENFORCER_PRIVATE_KEY_PATH=/home/wso2/security/keystore/mg.key
      - ENFORCER_PUBLIC_CERT_PATH=/home/wso2/security/keystore/mg.pem
      - TRUSTED_CA_CERTS_PATH=/home/wso2/security/truststore
      - ADAPTER_HOST_NAME=adapter
      - ADAPTER_HOST=adapter
      - ADAPTER_XDS_PORT=18000
      - ENFORCER_LABEL=Default
      - ENFORCER_REGION=UNKNOWN
      - XDS_MAX_MSG_SIZE=4194304
      - XDS_MAX_RETRIES=3
      - JAVA_OPTS=${JAVA_OPTS} -Dhttpclient.hostnameVerifier=AllowAll
      - apim_admin_pwd=admin
      - enforcer_admin_pwd=admin
      - tm_admin_pwd=admin
      - analytics_authURL=https://localhost:8080
      - analytics_authToken=
#    ports:
#      - "18081:8081"
#      - "19001:9001"
  router-mgw2:
    image: wso2/choreo-connect-router:1.1.0
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    environment:
      - ROUTER_ADMIN_HOST=0.0.0.0
      - ROUTER_ADMIN_PORT=9000
      - ROUTER_CLUSTER=default_cluster
      - ROUTER_LABEL=Internal
      - ROUTER_PRIVATE_KEY_PATH=/home/wso2/security/keystore/mg.key
      - ROUTER_PUBLIC_CERT_PATH=/home/wso2/security/keystore/mg.pem
      - ADAPTER_HOST=adapter-mgw2
      - ADAPTER_PORT=18000
      - ADAPTER_CA_CERT_PATH=/home/wso2/security/truststore/mg.pem
      - ENFORCER_HOST=enforcer-mgw2
      - ENFORCER_PORT=8081
      - ENFORCER_CA_CERT_PATH=/home/wso2/security/truststore/mg.pem
      - CONCURRENCY=2
    volumes:
      - ./resources/router/security:/home/wso2/security
    ports:
      - "29095:9095"
      - "29000:9000"
      - "29090:9090"
    links:
      - adapter-mgw2
      - enforcer-mgw2
  adapter-mgw2:
    image: wso2/choreo-connect-adapter:1.1.0
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./resources/adapter/security:/home/wso2/security
      - ./conf/log_config.toml:/home/wso2/conf/log_config.toml
      - ./conf/config_mgw2.toml:/home/wso2/conf/config.toml
    environment:
      - ADAPTER_PRIVATE_KEY_PATH=/home/wso2/security/keystore/mg.key
      - ADAPTER_PUBLIC_CERT_PATH=/home/wso2/security/keystore/mg.pem
      - cp_admin_pwd=admin
      - adapter_admin_pwd=admin
#    ports:
#      - "28000:18000"
#      - "29843:9843"
    links:
      - apim
  enforcer-mgw2:
    image: wso2/choreo-connect-enforcer:1.1.0
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./resources/enforcer/security:/home/wso2/security
      - ./conf/log4j2.properties:/home/wso2/conf/log4j2.properties
      #- ./resources/enforcer/dropins:/home/wso2/lib/dropins
    links:
      - adapter-mgw2
      - apim
    environment:
      - ENFORCER_PRIVATE_KEY_PATH=/home/wso2/security/keystore/mg.key
      - ENFORCER_PUBLIC_CERT_PATH=/home/wso2/security/keystore/mg.pem
      - TRUSTED_CA_CERTS_PATH=/home/wso2/security/truststore
      - ADAPTER_HOST_NAME=adapter
      - ADAPTER_HOST=adapter-mgw2
      - ADAPTER_XDS_PORT=18000
      - ENFORCER_LABEL=Internal
      - ENFORCER_REGION=UNKNOWN
      - XDS_MAX_MSG_SIZE=4194304
      - XDS_MAX_RETRIES=3
      - JAVA_OPTS=${JAVA_OPTS} -Dhttpclient.hostnameVerifier=AllowAll
      - apim_admin_pwd=admin
      - enforcer_admin_pwd=admin
      - tm_admin_pwd=admin
      - analytics_authURL=https://localhost:8080
      - analytics_authToken=
#    ports:
#      - "28081:8081"
#      - "29001:9001"
  sample-api-1:
    image: codegerm/mocky
    ports:
      - "4010:4010"
    environment:
      - PROFILE_NAME=control-plane
    volumes:
      - ./docker/openapi-specs/openapi-core-topology.yaml:/tmp/openapi-core-topology.yaml
    command:
      mock -h 0.0.0.0 /tmp/openapi-core-topology.yaml

  wso2-db:
      build: ./db/
      image: wso2/db
      hostname: wso2-db
#      volumes:
#        - ./dbstore:/var/lib/postgresql/data
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
#      ports:
#        - "51409:5432"
      command: ["postgres", "-c", "log_statement=all"]
